// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFjq6oDPr34lGee20bXzqAi2UFq3bGI78',
    appId: '1:365385138869:web:b1ee88be8910651ac9f4fc',
    messagingSenderId: '365385138869',
    projectId: 'chatbotenglish-df85d',
    authDomain: 'chatbotenglish-df85d.firebaseapp.com',
    storageBucket: 'chatbotenglish-df85d.firebasestorage.app',
    measurementId: 'G-Q71R56SS4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_JGwFFSVFniTyDwr4PPuXSR7kwJRcpSA',
    appId: '1:365385138869:android:a899f4b944eb2dc6c9f4fc',
    messagingSenderId: '365385138869',
    projectId: 'chatbotenglish-df85d',
    storageBucket: 'chatbotenglish-df85d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHUzIpLzEhPC-yKttBnZRC19H6bCagUdg',
    appId: '1:365385138869:ios:586fe745f6353697c9f4fc',
    messagingSenderId: '365385138869',
    projectId: 'chatbotenglish-df85d',
    storageBucket: 'chatbotenglish-df85d.firebasestorage.app',
    iosBundleId: 'com.example.chatbot3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHUzIpLzEhPC-yKttBnZRC19H6bCagUdg',
    appId: '1:365385138869:ios:586fe745f6353697c9f4fc',
    messagingSenderId: '365385138869',
    projectId: 'chatbotenglish-df85d',
    storageBucket: 'chatbotenglish-df85d.firebasestorage.app',
    iosBundleId: 'com.example.chatbot3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFjq6oDPr34lGee20bXzqAi2UFq3bGI78',
    appId: '1:365385138869:web:fc8b48956c9ae99ac9f4fc',
    messagingSenderId: '365385138869',
    projectId: 'chatbotenglish-df85d',
    authDomain: 'chatbotenglish-df85d.firebaseapp.com',
    storageBucket: 'chatbotenglish-df85d.firebasestorage.app',
    measurementId: 'G-GTJGYC0QW1',
  );
}
